# Generated by Django 4.2.14 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_static',
            field=models.CharField(blank=True, help_text='Static path under static/, eg: assets/placeholder-character-1.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
