# Generated by Django 4.2.14 on 2025-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_character_image_static_alter_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, help_text='Absolute URL to an image (http(s)://...)', null=True),
        ),
    ]
