# Generated by Django 4.2.14 on 2025-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_image_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL to the image (preferred)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
