# Generated by Django 4.2.14 on 2025-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_character_image_url_alter_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_static',
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL to the image'),
        ),
    ]
